connectIPVersion: v4
ports:
  dns: 127.0.0.1:53

upstream:
  default:
    - https://dns.libpcap.ru/dns-query
    - https://dns.cloudflare.com/dns-query
    - https://dns.quad9.net/dns-query

bootstrapDns:
  upstream: https://dns.libpcap.ru/dns-query
  ips:
    - 94.228.168.12

blocking:
  startStrategy: fast
  loading:
    maxErrorsPerSource: -1
  blackLists:
    ads:
      - https://libpcap.ru/blacklists/ads.txt
    privacy:
      - https://libpcap.ru/blacklists/privacy.txt

  clientGroupsBlock:
    default:
      - ads
      - privacy

